name: Build and Test

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --prefix .app

      - name: Build
        run: npm run build --prefix .app

      - name: Verify build output
        env:
          BUILD_OUTPUT_DIR: ".app/dist"
        run: |
          if [ -d "$BUILD_OUTPUT_DIR" ]; then
            echo "✅ Build succeeded - output directory exists"
            if [ "$(find $BUILD_OUTPUT_DIR -type f | wc -l)" -gt 0 ]; then
              echo "✅ Build output contains files"
            else
              echo "❌ Build output directory is empty"
              exit 1
            fi
          else
            echo "❌ Build failed - output directory does not exist"
            exit 1
          fi
